[project]
name = "odoo-addons-oca-l10n-mexico"
version = "19.0.20260816.1"
dependencies = [
    "odoo-addon-currency_rate_update_banxico==19.0.*",
    "odoo-addon-l10n_mx_account_reports==19.0.*",
    "odoo-addon-l10n_mx_catalogs==19.0.*",
    "odoo-addon-l10n_mx_catalogs_comex==19.0.*",
    "odoo-addon-l10n_mx_cfdi==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_audi==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_ford==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_kuehne_nagel==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_mabe==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_volkswagen==19.0.*",
    "odoo-addon-l10n_mx_cfdi_account_addenda_whirlpool==19.0.*",
    "odoo-addon-l10n_mx_cfdi_comex==19.0.*",
    "odoo-addon-l10n_mx_cfdi_waybill==19.0.*",
    "odoo-addon-l10n_mx_sat==19.0.*",
    "odoo-addon-l10n_mx_sat_vendor_bill==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
